### ISSUE TITLE
Befehle per MQTT? Einbindung in HA?

### ISSUE THREAD

**Issue by maijo366** [lumokitho/esp32-keyble#12]
Hallo,
Ich habe leider als Anfänger etwas Probleme damit. Es wurde von mir ein User angelegt und ich kann den ESP32 auch erreichen, bzw. bekomme ich auch die Statusmeldungen per IP des ESP. Leider kann ich weder mit der Togglefunktion am Button des ESP noch per Cmnd Befehle ausführen um das Schloss anzusteuern. Es tut sich einfach nichts. 
 
Per MQTT.fx sehe ich die Daten. Wenn ich den Toggle Button am ESP betätige steht kurz working. Am Schloss tut sich nichts. 
Wie lauten die genauen Befehle zum Ansteuern (Publish) des Schlosses, bzw. wie kann ich es Steuern.
Ich kann mit der Anleitung von [oyooyo](https://github.com/oyooyo)/[keyble](https://github.com/oyooyo/keyble) das Schloss steuern.

Was muss ich in HA in den config.Yaml und Sensor.yaml eintragen?
Ich möchte das Schloss in HA einbinden.

Den ESP32 habe ich mit PlatformiO geflasht.

Sehr viele Fragen und ich bin mittlerweile schon am verzweifeln.🤔

Bitte um Hilfe

**Comment by artur90226** [comment]
Hi, bist du weitergekommen? Ich stehe auch auf dem Schlauch.

**Comment by maijo366** [comment]
Ja endlich, es funktioniert.

> Hi, bist du weitergekommen? Ich stehe auch auf dem Schlauch.

**Comment by artur90226** [comment]
Kannst du mir da weiterhelfen? Ich bekomme keinen Status in mqtt Server

**Comment by maijo366** [comment]
> Kannst du mir da weiterhelfen? Ich bekomme keinen Status in mqtt Server

Gerne, wenn ichs kann ;-) deine emailadr.?

**Comment by artur90226** [comment]
> > Kannst du mir da weiterhelfen? Ich bekomme keinen Status in mqtt Server
> 
> Gerne, wenn ichs kann ;-) deine emailadr.?

artur.kaul@gmail.com
Benutzt du dieses Projekt oder von tc-maxx?

**Comment by sveba** [comment]
@maijo366 oder @artur90226  paste dein yaml einfach hier. Ich glaube da wären mehrere daran interessiert

**Comment by jelflein** [comment]
```
lock:
  - platform: mqtt
    name: Frontdoor
    state_topic: "lock/state"
    command_topic: "lock/command"
    payload_lock: "3"
    payload_unlock: "2"
    payload_open: "4"
    state_locked: "locked"
    state_unlocked: "unlocked"
    optimistic: false
    qos: 1
```
